"""Add priority field to transcriptions

Revision ID: 1b2949020db3
Revises: 7bbeeed291a9
Create Date: 2025-11-03 14:36:31.557529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2949020db3'
down_revision: Union[str, None] = '7bbeeed291a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(), nullable=False, server_default='medium'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
